#!/usr/bin/env bash
# Weekly quality report — run from repo root
# Usage: ./scripts/weekly_quality_report.sh [output_dir]
#
# Reads quality scores from environment variables (set by a real quality-run job).
# Without live scores, fields show N/A.
#
# Environment variables:
#   QUALITY_SQL_COVERAGE_SCORE   — float [0,1]
#   QUALITY_BLAST_RADIUS_SCORE   — float [0,1]
#   QUALITY_CITATION_SCORE       — float [0,1]
#   QUALITY_CONFIDENCE_SCORE     — float [0,1]
#   QUALITY_LATENCY_P50_SCORE    — float seconds
#   QUALITY_LATENCY_P90_SCORE    — float seconds
set -euo pipefail

OUTPUT_DIR="${1:-quality-reports}"
DATE=$(date +%Y-%m-%d)
REPORT_FILE="$OUTPUT_DIR/$DATE.md"

mkdir -p "$OUTPUT_DIR"

# Compute delta columns where scores are available
_delta() {
    local score="${1:-}"
    local baseline="${2:-}"
    if [ -z "$score" ] || [ "$score" = "N/A" ]; then
        echo "—"
        return
    fi
    # Use awk for floating-point arithmetic (bash doesn't support floats)
    awk -v s="$score" -v b="$baseline" 'BEGIN {
        delta = (s - b) / b * 100
        if (delta >= 0) printf "+%.1f%%\n", delta
        else printf "%.1f%%\n", delta
    }'
}

# Determine status emoji based on whether score meets threshold (>= baseline * 0.90)
_status() {
    local score="${1:-}"
    local baseline="${2:-}"
    if [ -z "$score" ] || [ "$score" = "N/A" ]; then
        echo "⏳ pending"
        return
    fi
    awk -v s="$score" -v b="$baseline" 'BEGIN {
        threshold = b * 0.90
        if (s >= threshold) print "✅ pass"
        else print "❌ fail"
    }'
}

# For latency: lower is better, so regression = measured > baseline * 1.10
_latency_status() {
    local score="${1:-}"
    local baseline="${2:-}"
    if [ -z "$score" ] || [ "$score" = "N/A" ]; then
        echo "⏳ pending"
        return
    fi
    awk -v s="$score" -v b="$baseline" 'BEGIN {
        threshold = b * 1.10
        if (s <= threshold) print "✅ pass"
        else print "❌ fail"
    }'
}

_latency_delta() {
    local score="${1:-}"
    local baseline="${2:-}"
    if [ -z "$score" ] || [ "$score" = "N/A" ]; then
        echo "—"
        return
    fi
    awk -v s="$score" -v b="$baseline" 'BEGIN {
        delta = (s - b) / b * 100
        # For latency, positive delta = regression (slower)
        if (delta >= 0) printf "+%.1f%% (slower)\n", delta
        else printf "%.1f%% (faster)\n", delta
    }'
}

SQL_SCORE="${QUALITY_SQL_COVERAGE_SCORE:-N/A}"
BLAST_SCORE="${QUALITY_BLAST_RADIUS_SCORE:-N/A}"
CITE_SCORE="${QUALITY_CITATION_SCORE:-N/A}"
CONF_SCORE="${QUALITY_CONFIDENCE_SCORE:-N/A}"
P50_SCORE="${QUALITY_LATENCY_P50_SCORE:-N/A}"
P90_SCORE="${QUALITY_LATENCY_P90_SCORE:-N/A}"

cat > "$REPORT_FILE" << REPORT
# Quality Report — $DATE

Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

## Metric Scores

| Metric | Score | Baseline | Delta | Status |
|--------|-------|----------|-------|--------|
| SQL Coverage | ${SQL_SCORE} | 0.75 | $(_delta "$SQL_SCORE" 0.75) | $(_status "$SQL_SCORE" 0.75) |
| Blast Radius Recall | ${BLAST_SCORE} | 0.65 | $(_delta "$BLAST_SCORE" 0.65) | $(_status "$BLAST_SCORE" 0.65) |
| Citation Rate | ${CITE_SCORE} | 1.0 | $(_delta "$CITE_SCORE" 1.0) | $(_status "$CITE_SCORE" 1.0) |
| Confidence Accuracy | ${CONF_SCORE} | 0.70 | $(_delta "$CONF_SCORE" 0.70) | $(_status "$CONF_SCORE" 0.70) |
| P50 Latency (s) | ${P50_SCORE} | 3.0 | $(_latency_delta "$P50_SCORE" 3.0) | $(_latency_status "$P50_SCORE" 3.0) |
| P90 Latency (s) | ${P90_SCORE} | 8.0 | $(_latency_delta "$P90_SCORE" 8.0) | $(_latency_status "$P90_SCORE" 8.0) |

## Regression Threshold

A metric is flagged as a regression when its score drops more than **10%** below baseline.
For latency, a regression is when P50 or P90 exceeds baseline by more than **10%**.

## How to get live scores

Run the full quality pipeline:

\`\`\`bash
QUALITY_RUN_LIVE=true \\
  QUALITY_SQL_COVERAGE_SCORE=<measured> \\
  QUALITY_BLAST_RADIUS_SCORE=<measured> \\
  QUALITY_CITATION_SCORE=<measured> \\
  QUALITY_CONFIDENCE_SCORE=<measured> \\
  QUALITY_LATENCY_P50_SCORE=<measured> \\
  QUALITY_LATENCY_P90_SCORE=<measured> \\
  ./scripts/weekly_quality_report.sh
\`\`\`

## Notes

- Report generated by \`scripts/weekly_quality_report.sh\`
- Golden sets: \`company-brain-ai/tests/quality/golden_sets/\`
- CI gate: \`.github/workflows/quality-gate.yml\`
REPORT

echo "Report written to $REPORT_FILE"
